version: 2
updates:
  - package-ecosystem: docker
    directory: /housekeeper_agent
    schedule: {interval: weekly}
  - package-ecosystem: github-actions
    directory: /
    schedule: {interval: weekly}
